---
driver:
  name: vagrant

provisioner:
  name: chef_solo

verifier:
  name: inspec

platforms:
  - name: windows_2008_r2
    driver_config:
      communicator: winrm
    transport:
      name: winrm
  - name: windows_2008_r2_core
    driver_config:
      communicator: winrm
    transport:
      name: winrm
  - name: windows_2012
    driver_config:
      communicator: winrm
    transport:
      name: winrm
  - name: windows_2012_core
    driver_config:
      communicator: winrm
    transport:
      name: winrm      
  - name: windows_2012_r2
    driver_config:
      communicator: winrm
    transport:
      name: winrm
  - name: windows_2012_r2_core
    driver_config:
      communicator: winrm
    transport:
      name: winrm

suites:
  - name: default
    run_list:
      - recipe[test_windows_ad::setup_dc]
    attributes:
  - name: ad-objects
    run_list:
      - recipe[test_windows_ad::setup_dc]
      - recipe[test_windows_ad::ou]
      - recipe[test_windows_ad::group]


